#include "dedup.h"
/*  dedup.c - The simplest kernel module.
 */

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Insu Jang, Seikown Kim, and Seonyoung Lee");
MODULE_DESCRIPTION
    ("dedup - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "dedup"


static irqreturn_t dedup_irq(int irq, void *lp)
{
	printk("dedup interrupt\n");
	return IRQ_HANDLED;
}

static int dedup_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	
    int rc = 0;
	
	dev_info(dev, "Device Tree Probing\n");

	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	
	lp = (struct dedup_local *) kmalloc(sizeof(struct dedup_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate dedup device\n");
		return -ENOMEM;
	}
	
	dev_set_drvdata(dev, lp);
	
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "dedup: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "dedup at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	
	rc = request_irq(lp->irq, &dedup_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"dedup at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int dedup_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct dedup_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id dedup_of_match[] = {
	{ .compatible = "xlnx,dedupDriver-1.0", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, dedup_of_match);
#else
# define dedup_of_match
#endif


static struct platform_driver dedup_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= dedup_of_match,
	},
	.probe		= dedup_probe,
	.remove		= dedup_remove,
};

static int __init dedup_init(void)
{
	printk("Dedup device driver initializing.\n");
    chrdev_initialize();
	return platform_driver_register(&dedup_driver);
}


static void __exit dedup_exit(void)
{
    chrdev_destroy();
	platform_driver_unregister(&dedup_driver);
	printk(KERN_ALERT "Dedup device driver is detached.\n");
}

module_init(dedup_init);
module_exit(dedup_exit);

