// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCALCHASH_H
#define XCALCHASH_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xcalchash_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XCalchash_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XCalchash;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XCalchash_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XCalchash_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XCalchash_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XCalchash_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XCalchash_Initialize(XCalchash *InstancePtr, u16 DeviceId);
XCalchash_Config* XCalchash_LookupConfig(u16 DeviceId);
int XCalchash_CfgInitialize(XCalchash *InstancePtr, XCalchash_Config *ConfigPtr);
#else
int XCalchash_Initialize(XCalchash *InstancePtr, const char* InstanceName);
int XCalchash_Release(XCalchash *InstancePtr);
#endif

void XCalchash_Start(XCalchash *InstancePtr);
u32 XCalchash_IsDone(XCalchash *InstancePtr);
u32 XCalchash_IsIdle(XCalchash *InstancePtr);
u32 XCalchash_IsReady(XCalchash *InstancePtr);
void XCalchash_EnableAutoRestart(XCalchash *InstancePtr);
void XCalchash_DisableAutoRestart(XCalchash *InstancePtr);


void XCalchash_InterruptGlobalEnable(XCalchash *InstancePtr);
void XCalchash_InterruptGlobalDisable(XCalchash *InstancePtr);
void XCalchash_InterruptEnable(XCalchash *InstancePtr, u32 Mask);
void XCalchash_InterruptDisable(XCalchash *InstancePtr, u32 Mask);
void XCalchash_InterruptClear(XCalchash *InstancePtr, u32 Mask);
u32 XCalchash_InterruptGetEnabled(XCalchash *InstancePtr);
u32 XCalchash_InterruptGetStatus(XCalchash *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
