// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdedupdriver.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDedupdriver_CfgInitialize(XDedupdriver *InstancePtr, XDedupdriver_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDedupdriver_Start(XDedupdriver *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDedupdriver_ReadReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_AP_CTRL) & 0x80;
    XDedupdriver_WriteReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDedupdriver_IsDone(XDedupdriver *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDedupdriver_ReadReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDedupdriver_IsIdle(XDedupdriver *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDedupdriver_ReadReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDedupdriver_IsReady(XDedupdriver *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDedupdriver_ReadReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDedupdriver_EnableAutoRestart(XDedupdriver *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDedupdriver_WriteReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XDedupdriver_DisableAutoRestart(XDedupdriver *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDedupdriver_WriteReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_AP_CTRL, 0);
}

void XDedupdriver_InterruptGlobalEnable(XDedupdriver *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDedupdriver_WriteReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_GIE, 1);
}

void XDedupdriver_InterruptGlobalDisable(XDedupdriver *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDedupdriver_WriteReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_GIE, 0);
}

void XDedupdriver_InterruptEnable(XDedupdriver *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDedupdriver_ReadReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_IER);
    XDedupdriver_WriteReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_IER, Register | Mask);
}

void XDedupdriver_InterruptDisable(XDedupdriver *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDedupdriver_ReadReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_IER);
    XDedupdriver_WriteReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_IER, Register & (~Mask));
}

void XDedupdriver_InterruptClear(XDedupdriver *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDedupdriver_WriteReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_ISR, Mask);
}

u32 XDedupdriver_InterruptGetEnabled(XDedupdriver *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDedupdriver_ReadReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_IER);
}

u32 XDedupdriver_InterruptGetStatus(XDedupdriver *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDedupdriver_ReadReg(InstancePtr->Axilites_BaseAddress, XDEDUPDRIVER_AXILITES_ADDR_ISR);
}

