// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdedupdriver.h"

extern XDedupdriver_Config XDedupdriver_ConfigTable[];

XDedupdriver_Config *XDedupdriver_LookupConfig(u16 DeviceId) {
	XDedupdriver_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDEDUPDRIVER_NUM_INSTANCES; Index++) {
		if (XDedupdriver_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDedupdriver_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDedupdriver_Initialize(XDedupdriver *InstancePtr, u16 DeviceId) {
	XDedupdriver_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDedupdriver_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDedupdriver_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

