// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "strStream_V"
#define AUTOTB_TVIN_strStream_V  "../tv/cdatafile/c.calcHash.autotvin_strStream_V.dat"
#define WRAPC_STREAM_SIZE_IN_strStream_V  "../tv/stream_size/stream_size_in_strStream_V.dat"
#define WRAPC_STREAM_INGRESS_STATUS_strStream_V  "../tv/stream_size/stream_ingress_status_strStream_V.dat"
// wrapc file define: "indicesStream_V"
#define AUTOTB_TVOUT_indicesStream_V  "../tv/cdatafile/c.calcHash.autotvout_indicesStream_V.dat"
#define AUTOTB_TVIN_indicesStream_V  "../tv/cdatafile/c.calcHash.autotvin_indicesStream_V.dat"
#define WRAPC_STREAM_SIZE_OUT_indicesStream_V  "../tv/stream_size/stream_size_out_indicesStream_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_indicesStream_V  "../tv/stream_size/stream_egress_status_indicesStream_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "indicesStream_V"
#define AUTOTB_TVOUT_PC_indicesStream_V  "../tv/rtldatafile/rtl.calcHash.autotvout_indicesStream_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			strStream_V_depth = 0;
			indicesStream_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{strStream_V " << strStream_V_depth << "}\n";
			total_list << "{indicesStream_V " << indicesStream_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int strStream_V_depth;
		int indicesStream_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define calcHash AESL_ORIG_DUT_calcHash
extern void calcHash (
hls::stream<char >& strStream,
hls::stream<int >& indicesStream);
#undef calcHash

void calcHash (
hls::stream<char >& strStream,
hls::stream<int >& indicesStream)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		// pop stream input: "strStream"
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_strStream_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_strStream_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_strStream_V, AESL_token); // pop_size
			int aesl_tmp_1 = atoi(AESL_token.c_str());
			for (int i = 0; i < aesl_tmp_1; i++)
			{
				strStream.read();
			}
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_strStream_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "indicesStream"
		std::vector<int > aesl_tmp_3;
		int aesl_tmp_4;
		int aesl_tmp_5 = 0;

		// read output stream size: "indicesStream"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_indicesStream_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_indicesStream_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_indicesStream_V, AESL_token); // pop_size
			aesl_tmp_4 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_indicesStream_V, AESL_token); // [[/transaction]]
		}

		// output port post check: "indicesStream_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_indicesStream_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_indicesStream_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_indicesStream_V, AESL_token); // data

			std::vector<sc_bv<32> > indicesStream_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'indicesStream_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'indicesStream_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					indicesStream_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_indicesStream_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_indicesStream_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_4)
			{
				aesl_tmp_4 = i;
			}

			if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4)
			{
				int aesl_tmp_3_size = aesl_tmp_3.size();

				for (int tmp_aesl_tmp_3 = 0; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size; tmp_aesl_tmp_3++)
				{
					int tmp;
					aesl_tmp_3.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: indicesStream_V
				{
					// bitslice(31, 0)
					// {
						// celement: indicesStream.V(31, 0)
						// {
							sc_lv<32>* indicesStream_V_lv0_0_0_1 = new sc_lv<32>[aesl_tmp_4 - aesl_tmp_5];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: indicesStream.V(31, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
								{
									indicesStream_V_lv0_0_0_1[hls_map_index++].range(31, 0) = sc_bv<32>(indicesStream_V_pc_buffer[hls_map_index].range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: indicesStream.V(31, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : aesl_tmp_3[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : aesl_tmp_3[0]
								// output_left_conversion : aesl_tmp_3[i_0]
								// output_type_conversion : (indicesStream_V_lv0_0_0_1[hls_map_index++]).to_uint64()
								if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
								{
									aesl_tmp_3[i_0] = (indicesStream_V_lv0_0_0_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		// push back output stream: "indicesStream"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			indicesStream.write(aesl_tmp_3[i]);
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "strStream_V"
		char* tvin_strStream_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_strStream_V);
		char* wrapc_stream_size_in_strStream_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_IN_strStream_V);
		char* wrapc_stream_ingress_status_strStream_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_INGRESS_STATUS_strStream_V);

		// "indicesStream_V"
		char* tvin_indicesStream_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_indicesStream_V);
		char* tvout_indicesStream_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_indicesStream_V);
		char* wrapc_stream_size_out_indicesStream_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_indicesStream_V);
		char* wrapc_stream_egress_status_indicesStream_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_indicesStream_V);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// dump stream tvin: "strStream"
		std::vector<char > aesl_tmp_0;
		int aesl_tmp_1 = 0;
		while (!strStream.empty())
		{
			aesl_tmp_0.push_back(strStream.read());
			aesl_tmp_1++;
		}

		// dump stream tvin: "indicesStream"
		std::vector<int > aesl_tmp_3;
		int aesl_tmp_4 = 0;
		while (!indicesStream.empty())
		{
			aesl_tmp_3.push_back(indicesStream.read());
			aesl_tmp_4++;
		}

		// push back input stream: "strStream"
		for (int i = 0; i < aesl_tmp_1; i++)
		{
			strStream.write(aesl_tmp_0[i]);
		}

		// push back input stream: "indicesStream"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			indicesStream.write(aesl_tmp_3[i]);
		}

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		AESL_ORIG_DUT_calcHash(strStream, indicesStream);

		CodeState = DUMP_OUTPUTS;
		// record input size to tv3: "strStream"
		int aesl_tmp_2 = strStream.size();

		// pop output stream: "indicesStream"
		int aesl_tmp_5 = aesl_tmp_4;
		aesl_tmp_4 = 0;
     aesl_tmp_3.clear();
		while (!indicesStream.empty())
		{
			aesl_tmp_3.push_back(indicesStream.read());
			aesl_tmp_4++;
		}

		// [[transaction]]
		sprintf(tvin_strStream_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_strStream_V, tvin_strStream_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_strStream_V, tvin_strStream_V);

		sc_bv<8>* strStream_V_tvin_wrapc_buffer = new sc_bv<8>[aesl_tmp_1 - aesl_tmp_2];

		// RTL Name: strStream_V
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: strStream.V(7, 0)
				{
					// carray: (0) => (aesl_tmp_1 - aesl_tmp_2 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : aesl_tmp_0[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : aesl_tmp_0[0]
						// regulate_c_name       : strStream_V
						// input_type_conversion : aesl_tmp_0[i_0]
						if (&(aesl_tmp_0[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> strStream_V_tmp_mem;
							strStream_V_tmp_mem = aesl_tmp_0[i_0];
							strStream_V_tvin_wrapc_buffer[hls_map_index++].range(7, 0) = strStream_V_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			sprintf(tvin_strStream_V, "%s\n", (strStream_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_strStream_V, tvin_strStream_V);
		}

		// dump stream ingress status to file
		sc_int<32> stream_ingress_size_strStream_V = aesl_tmp_1;
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_strStream_V, stream_ingress_size_strStream_V.to_string().c_str());
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_strStream_V, "\n");

		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			stream_ingress_size_strStream_V--;
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_strStream_V, stream_ingress_size_strStream_V.to_string().c_str());
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_strStream_V, "\n");
		}

		tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2, &tcl_file.strStream_V_depth);
		sprintf(tvin_strStream_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_strStream_V, tvin_strStream_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_strStream_V, tvin_strStream_V);

		// release memory allocation
		delete [] strStream_V_tvin_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_in_strStream_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_strStream_V, wrapc_stream_size_in_strStream_V);
		sprintf(wrapc_stream_size_in_strStream_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_strStream_V, wrapc_stream_size_in_strStream_V);
		sprintf(wrapc_stream_size_in_strStream_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_strStream_V, wrapc_stream_size_in_strStream_V);

		// [[transaction]]
		sprintf(tvout_indicesStream_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_indicesStream_V, tvout_indicesStream_V);

		sc_bv<32>* indicesStream_V_tvout_wrapc_buffer = new sc_bv<32>[aesl_tmp_4 - aesl_tmp_5];

		// RTL Name: indicesStream_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: indicesStream.V(31, 0)
				{
					// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
					for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : aesl_tmp_3[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : aesl_tmp_3[0]
						// regulate_c_name       : indicesStream_V
						// input_type_conversion : aesl_tmp_3[i_0]
						if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> indicesStream_V_tmp_mem;
							indicesStream_V_tmp_mem = aesl_tmp_3[i_0];
							indicesStream_V_tvout_wrapc_buffer[hls_map_index++].range(31, 0) = indicesStream_V_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			sprintf(tvout_indicesStream_V, "%s\n", (indicesStream_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_indicesStream_V, tvout_indicesStream_V);
		}

		tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5, &tcl_file.indicesStream_V_depth);
		sprintf(tvout_indicesStream_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_indicesStream_V, tvout_indicesStream_V);

		// release memory allocation
		delete [] indicesStream_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_indicesStream_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_indicesStream_V, wrapc_stream_size_out_indicesStream_V);
		sprintf(wrapc_stream_size_out_indicesStream_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_indicesStream_V, wrapc_stream_size_out_indicesStream_V);
		sprintf(wrapc_stream_size_out_indicesStream_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_indicesStream_V, wrapc_stream_size_out_indicesStream_V);

		// push back output stream: "indicesStream"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			indicesStream.write(aesl_tmp_3[i]);
		}

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "strStream_V"
		delete [] tvin_strStream_V;
		delete [] wrapc_stream_size_in_strStream_V;
		// release memory allocation: "indicesStream_V"
		delete [] tvout_indicesStream_V;
		delete [] tvin_indicesStream_V;
		delete [] wrapc_stream_size_out_indicesStream_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

