// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XDEDUPDRIVER_H
#define XDEDUPDRIVER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdedupdriver_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XDedupdriver_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XDedupdriver;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDedupdriver_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDedupdriver_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDedupdriver_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDedupdriver_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDedupdriver_Initialize(XDedupdriver *InstancePtr, u16 DeviceId);
XDedupdriver_Config* XDedupdriver_LookupConfig(u16 DeviceId);
int XDedupdriver_CfgInitialize(XDedupdriver *InstancePtr, XDedupdriver_Config *ConfigPtr);
#else
int XDedupdriver_Initialize(XDedupdriver *InstancePtr, const char* InstanceName);
int XDedupdriver_Release(XDedupdriver *InstancePtr);
#endif

void XDedupdriver_Start(XDedupdriver *InstancePtr);
u32 XDedupdriver_IsDone(XDedupdriver *InstancePtr);
u32 XDedupdriver_IsIdle(XDedupdriver *InstancePtr);
u32 XDedupdriver_IsReady(XDedupdriver *InstancePtr);
void XDedupdriver_EnableAutoRestart(XDedupdriver *InstancePtr);
void XDedupdriver_DisableAutoRestart(XDedupdriver *InstancePtr);


void XDedupdriver_InterruptGlobalEnable(XDedupdriver *InstancePtr);
void XDedupdriver_InterruptGlobalDisable(XDedupdriver *InstancePtr);
void XDedupdriver_InterruptEnable(XDedupdriver *InstancePtr, u32 Mask);
void XDedupdriver_InterruptDisable(XDedupdriver *InstancePtr, u32 Mask);
void XDedupdriver_InterruptClear(XDedupdriver *InstancePtr, u32 Mask);
u32 XDedupdriver_InterruptGetEnabled(XDedupdriver *InstancePtr);
u32 XDedupdriver_InterruptGetStatus(XDedupdriver *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
