// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcalchash.h"

extern XCalchash_Config XCalchash_ConfigTable[];

XCalchash_Config *XCalchash_LookupConfig(u16 DeviceId) {
	XCalchash_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCALCHASH_NUM_INSTANCES; Index++) {
		if (XCalchash_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCalchash_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCalchash_Initialize(XCalchash *InstancePtr, u16 DeviceId) {
	XCalchash_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCalchash_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCalchash_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

