/*  hello.c - The simplest kernel module.
 */
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

#include <linux/fs.h>
#include <linux/cdev.h>
#include <linux/device.h>
#include <linux/types.h>
#include <asm/io.h>


/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Insu Jang");
MODULE_DESCRIPTION
    ("hello - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "hello"

struct hello_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

struct hello_local *lp = NULL;

//static irqreturn_t hello_irq(int irq, void *lp, struct pt_regs *regs)
static irqreturn_t hello_irq(int irq, void *lp)
{
	printk("hello interrupt. irq: %d\n", irq);
    // Clear the interrupt by writing any value to the interrupt status register (ISR).
    iowrite32(1, ((struct hello_local *)lp)->base_addr + 0xc);	
    return IRQ_HANDLED;
}

static int hello_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	// struct hello_local *lp = NULL;
	
    int rc = 0;
	
	dev_info(dev, "Device Tree Probing\n");

	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	
	lp = (struct hello_local *) kmalloc(sizeof(struct hello_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate hello device\n");
		return -ENOMEM;
	}
	
	dev_set_drvdata(dev, lp);
	
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "hello: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "hello at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	
	rc = request_irq(lp->irq, &hello_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"hello at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int hello_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	// struct hello_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id hello_of_match[] = {
	{ .compatible = "xlnx,adder-1.0", },
	{ /* end of list */ },
};
// MODULE_DEVICE_TABLE(of, hello_of_match);
#else
# define hello_of_match
#endif


static struct platform_driver hello_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= hello_of_match,
	},
	.probe		= hello_probe,
	.remove		= hello_remove,
};

static int device_open(struct inode *inode, struct file *file){
    u32 reg;
    
    printk(KERN_INFO "device_open(%p)\n", file);

    // Disable auto restart functionality
    iowrite32(0, lp->base_addr);

    // Enable global interrupt (the interrupt output)
    iowrite32(1, lp->base_addr + 0x4);

    // Enable interrupt source for ap_done
    reg = ioread32(lp->base_addr + 0x8);
    iowrite32(reg | 0x1, lp->base_addr + 0x8);

    try_module_get(THIS_MODULE);
    return 0;
}

static int device_release(struct inode *inode, struct file *file){
    printk(KERN_INFO "device_release(%p,%p)\n", inode, file);

    module_put(THIS_MODULE);
    return 0;
}

static ssize_t device_read(struct file *file, char __user *buffer,
                            size_t length, loff_t *offset){
    printk(KERN_INFO "device_read\n");

    return length;
}

static ssize_t device_write(struct file *file, const char __user *buffer,
                            size_t length, loff_t *offset){
    u32 reg;
    
    printk(KERN_INFO "device_write\n");

    reg = ioread32(lp->base_addr);
    printk("ap_start: %d\n", reg & 0x1);
    printk("ap_done: %d\n", (reg >> 1) & 0x1);
    printk("ap_idle: %d\n", (reg >> 2) & 0x1);
    printk("ap_ready: %d\n", !(reg & 0x1));

    // Initiate interrupt reset
    iowrite32(reg | 0x1, lp->base_addr);

    return length;
}

static struct file_operations Fops = {
    .owner = THIS_MODULE,
    .read = device_read,
    .write = device_write,
    .open = device_open,
    .release = device_release,
};


static struct class *chardevice_class = NULL;
static dev_t dev;
static struct cdev cdevice;

static int __init hello_init(void)
{
	int rc;

    printk("<1>Hello module world.\n");

    // Get a range of minor numbers (starting with 0) to work with
    rc = alloc_chrdev_region(&dev, 0, 1, DRIVER_NAME);
    if(rc < 0){
        printk(KERN_ERR "Unable to allocate character device region.\n");
        return rc;
    }
    printk(KERN_INFO "Successfully get a range of minor numbers.\n");

    // Create device class (before allocation of the array of devices)
    chardevice_class = class_create(THIS_MODULE, DRIVER_NAME);
    if(IS_ERR(DRIVER_NAME)){
        printk(KERN_ERR "Unable to create a device class.\n");
        unregister_chrdev_region(dev, 1);
        return -1;
    }
    printk(KERN_INFO "Successfully created device class.\n");

    // Create a device for our module. This will create a file on /dev/hello.
    if(device_create(chardevice_class, NULL, dev, NULL, DRIVER_NAME) == NULL){
        printk(KERN_ERR "Unable to add a character device.\n");
        class_destroy(chardevice_class);
        unregister_chrdev_region(dev, 1);
        return -1;
    }
    printk(KERN_INFO "Successfully created a device.\n");

    // Register our character device with the kernel
    cdev_init(&cdevice, &Fops);
    rc = cdev_add(&cdevice, dev, 1);
    if(rc < 0){
        printk(KERN_ERR "Unable to add a character device.\n");
        device_destroy(chardevice_class, dev);
        class_destroy(chardevice_class);
        unregister_chrdev_region(dev, 1);
        return rc;
    }
    printk(KERN_INFO "Successfully created a character device.\n");

    // hello_device.major_num = register_chrdev(0, DRIVER_NAME, &Fops);
    // printk(KERN_INFO "major num: %d\n", hello_device.major_num);

	return platform_driver_register(&hello_driver);
}


static void __exit hello_exit(void)
{
    unregister_chrdev(dev, DRIVER_NAME);
	platform_driver_unregister(&hello_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(hello_init);
module_exit(hello_exit);

