# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/insujang/cs710/xilinx_workspace/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/insujang/cs710/xilinx_workspace/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/insujang/cs710/xilinx_hls_workspace [current_project]
add_files /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_1/design_1_rst_processing_system7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_1/design_1_rst_processing_system7_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_1/design_1_rst_processing_system7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_calcHash_0_0/constraints/calcHash_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0_1/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0_1/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0_1/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib /home/insujang/cs710/xilinx_workspace/project_1/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
