all: main.cpp
	export __linux__ && arm-linux-gnueabihf-g++ -o axidma_test main.cpp \
	-I/home/insujang/cs710/dma/xilinx_axidma/include \
	-I/home/insujang/cs710/dma/xilinx_axidma/examples \
	-L/home/insujang/cs710/dma/xilinx_axidma/library -laxidma
