// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcalchash.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCalchash_CfgInitialize(XCalchash *InstancePtr, XCalchash_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCalchash_Start(XCalchash *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalchash_ReadReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_AP_CTRL) & 0x80;
    XCalchash_WriteReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCalchash_IsDone(XCalchash *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalchash_ReadReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCalchash_IsIdle(XCalchash *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalchash_ReadReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCalchash_IsReady(XCalchash *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCalchash_ReadReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCalchash_EnableAutoRestart(XCalchash *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalchash_WriteReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XCalchash_DisableAutoRestart(XCalchash *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalchash_WriteReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_AP_CTRL, 0);
}

void XCalchash_InterruptGlobalEnable(XCalchash *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalchash_WriteReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_GIE, 1);
}

void XCalchash_InterruptGlobalDisable(XCalchash *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalchash_WriteReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_GIE, 0);
}

void XCalchash_InterruptEnable(XCalchash *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCalchash_ReadReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_IER);
    XCalchash_WriteReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_IER, Register | Mask);
}

void XCalchash_InterruptDisable(XCalchash *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCalchash_ReadReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_IER);
    XCalchash_WriteReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_IER, Register & (~Mask));
}

void XCalchash_InterruptClear(XCalchash *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCalchash_WriteReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_ISR, Mask);
}

u32 XCalchash_InterruptGetEnabled(XCalchash *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCalchash_ReadReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_IER);
}

u32 XCalchash_InterruptGetStatus(XCalchash *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCalchash_ReadReg(InstancePtr->Axilites_BaseAddress, XCALCHASH_AXILITES_ADDR_ISR);
}

